#!/bin/bash

cd /usr/bin || exit

for i in $(cat /var/lib/package-manager/pak);do
    add=/usr/bin/
    add+=$i
    bina+=($add)
done

#convert found files into options for dialog
cnt=1
for a in ${bina[*]}; do
    param+=("$cnt" "$a" "off")
    cnt=$((cnt + 1))
done

#dialog
temp=$(mktemp)
if dialog --checklist "select what you want to uninstall" 0 0 5 ${param[*]} 2> "$temp"; then
remove=$(cat "$temp") #turn the output from dialog back to a var

rm "$temp" #remove the tmp file
echo "$remove"
read -ra remove <<< "$remove"
echo remove
for a in ${remove[*]};do
    echo "$a"
done
echo bina
for a in ${bina[*]};do
    echo "$a"
done

echo removing
for a in ${remove[@]};do
    rm "${bina["$((a - 1))"]}"
    echo "${bina["$((a - 1))"]}"
    sed -i "$a"d /var/lib/package-manager/pak
done
exit
fi
clear
rm "$temp"
echo "dialog was canceled"
