#!/usr/bin/env bash
pwd
cd src 
#compile and add a custom header to the file
for i in $(pwd)/*; do
    shc -f $i
done

#move to folders
mv *.x ../bin
mv *.x.c ../c

#clear file extensions
cd ../bin
for i in $(pwd)/*; do
    for o in $(pwd)/*;
    do
        name=${o%.*}
        mv $o $name 2>/dev/null
    done    
done

for i in $(pwd)/*;do
    echo $i
done

