#!/bin/bash

scompile () {
echo "#!/bin/bash" > ../$1
echo "shift $2" >> ../$1
echo "case \$1 in" >> ../$1
}
compile () {
for f in *;do
    echo $f compile to $1
    if [[ -d $f ]];then
        echo $f is directory
    else
        echo "$f)" >> ../$1
        sed 1d $f >> ../$1
        echo ";;" >> ../$1
    fi
done
}
ecompile () {
echo "*)" >>../$1
echo "echo subcommand not found" >> ../$1
echo "esac" >> ../$1
}

recursion () {
echo re $1
a=$1
if ls -d */;then
    n=$((a + 1))
    for f in */;do
        cd $f
        pwd
        echo layer $n
        recursion $n
    done
fi
name=$(basename $(pwd)).tmp
scompile $name $n
compile $name
ecompile $name
echo +1
cd ..
}
cd walsrc
recursion 0
mv walsrc.tmp walpak
chmod +x walpak
pwd


