#!/usr/bin/env bash
while [[ "$#" -gt "0" ]]; do
	case "$1" in
		--*=*)
			key=$(echo "$1" | awk -F "=" '{print $1}')
			value=$(echo "$1" | awk -F "=" '{print $2}')
			eval "export '${key: 2}'='$value'"
		;;
		--*)
            if [[ -n "$2" ]];then
    			eval "export '${1: 2}'='$2'"
	    		shift 1
            else
                eval "export '${1:2}'='1'"
            fi
		;;
		-*)
			eval "export '${1: 1}'='1'"
		;;
	esac
	shift 1
done
