#!/usr/bin/env bash

if sch -h >/dev/null 2>&1 ;then
	true
else
	echo "'shc' is not installed."
	echo "'shc' can be installed if you have https://github.com/walksanatora/pm-repo-main"
	echo "just run 'walpak install shc'"
fi
