#!/bin/bash
if echo "$PATH" | grep "$HOME"/.local/bin; then
    echo "install location is in path"
else
    echo "adding to .bashrc the path or install"
    echo "export PATH=\"\$HOME/.local/bin:\$PATH\"" >> ~/.bashrc
    echo "~/.local/bin has been added to path"
fi

#check for fish shell
if echo "$SHELL" | grep fish;then
    fish -c "set -ag PATH $HOME/.local/bin"
fi

if test -e $HOME/.local/bin;then
    echo "~/.local/bin exist skipping"
else
        echo "creating ~/.local/bin"
    mkdir $HOME/.local/bin
    echo "done"
fi

if test -e $HOME/.local/var;then
    echo "~/.local/var exist skipping"
else
    echo "creating ~/.local/var"
    mkdir $HOME/.local/var
    echo "done"
fi

if test -e $HOME/.local/var/package-manager;then
    echo "~/.local/var/package-manager exist skipping"
else
    echo "creating ~/.local/var/package-manger"
    mkdir $HOME/.local/var/package-manager
    echo "done"
fi


echo "installing man pages"
pwd
ls -lsah
mv -f "$(pwd)/man/" "~/.local/man/"
