#!/bin/bash

cd $HOME/.local/bin || exit

pkg="$HOME/.local/var/package-manager/pak"

cvar=$(sort $pkg | uniq )
for i in ${cvar[*]};do
echo $i
done
read
for i in $(cat $pkg);do
    add=$HOME/.local/bin/
    add+=$i
    bina+=($add)
done

#convert found files into options for dialog
cnt=1
for a in $(cat $pkg); do
    param+=("$cnt" "$a" "off")
    cnt=$((cnt + 1))
done

#dialog
temp=$(mktemp)
if dialog --checklist "select what you want to uninstall" 0 0 5 ${param[*]} 2> "$temp"; then
remove=$(cat "$temp") #turn the output from dialog back to a var

rm "$temp" #remove the tmp file

read -ra remove <<< "$remove"
cnt=0
for a in "${remove[@]}";do
    rm "${bina["$((a - 1))"]}"
    echo "${bina["$((a - 1))"]}"
    a=$((a - cnt))
    sed -i "$a"d $pkg
    echo $a
    cnt=$((cnt + 1))
done
exit
fi
#clear
rm "$temp"
echo "dialog was canceled"
