#!/usr/bin/env bash
if grep -E "^$1$" "$HOME/.local/var/walpak/packages.installed";then
	if [[ -e "$HOME/.local/var/walpak/packages/$1" ]];then
		while read -r line; do
			type=$(echo "$line" | awk '{print $1}')
			path=$(echo "$line" | awk '{print $2}')
			case $type in
				d)
					echo "removing dir: $path"
					rm -r "$path"
				;;
				f)
					echo "removing file: $path"
					rm "$path"
				;;
			esac
		done < "$HOME/.local/var/walpak/packages/$1"
		sed -i "/^$1$/d" "$HOME/.local/var/walpak/packages.installed"
	else
		echo "packge has created no file list, please write them"
		echo "removing installed status anyways"
		sed -i "/^$1$/d" "$HOME/.local/var/walpak/packages.installed"
	fi
else
	echo "package '$1' does not appear to be installed"
fi
