#!/bin/bash
cd bin
rm *
cd ../c
rm *
echo "/bin and /c have been cleared"
echo "wanna clear installed packages"
echo "press enter or if you dont jsut exit the program"
read
for f in $(cat $HOME/.local/var/package-manager/pak);do
    rm $HOME/.local/bin/$f
done
